### ISSUE TITLE
spike: decide how we want to implement baseuri updateability

### ISSUE THREAD

**Issue by sabotagebeats** [Ninjagod1251/erc721project#3]
1. do we want these nft's to have pre-reveal coming soon image?
2. if we do, then we will need to make an additional variable pre-reveal uri
3. also the base uri updateable and it should be able to be zero
4. if we do this then we can set the tokenuri to return just the pre-reveal uri if the length of baseuri is 0
5. then we would need a function to be able to update the baseuri 
6. the prereveal uri would be set in the deployment
7. if the length of the baseuri is greater than zero, then we will return the baseuri + "/" + tokenID 

talk more next week about this @Ninjagod1251

**Comment by Ninjagod1251** [comment]
https://github.com/ApeWorX/ape/issues/912

**Comment by sabotagebeats** [comment]
@Ninjagod1251 is this issue resolved?
